common:
  host: "192.168.75.128"
  user: "test99"
  ssh-port: 22
  password: "testpwd"
  use-sudo: false
  use-rsync: false
  silent: false

upload:
  assets-root: "AAA/assets"
  properties-file: "AAA/config/path-mapping.properties"

patch:
  local-patch: "AAA/assets/example-patch.txt"
  remote-upload: "~/tmp/example-patch.txt.upload"
  remote-file: "~/examples/example-patch-remote.txt"
  remote-backup: "~/tmp/example-patch-remote.txt.bak"

execute:
  remote-path: "~"