
servers:
  - name: "server1"
    host: "192.168.75.128"
    user: "test99"
    ssh-port: 22
    password: "testpwd"
    connect_timeout: 60s  
  # - name: "server2"
  #   host: "192.168.75.128"
  #   user: "test99"
  #   ssh-port: 22
  #   password: "testpwd"
  #   connect_timeout: 30s  
vars:
  ASSETS_ROOT: "/mnt/c/Users/saidake/Desktop/DevProjects/sbxctl/AAA/assets"

groups:
  dev: ["server1"]
  uat: ["server1"]

configs:   
  - name: "dev-deploy"   
    
    # Common config
    use-sudo: false    
    use-rsync: false
    silent: false
    log-level: info
    
    upload:
      - properties-file: "AAA/config/path-mapping.properties"

        # You can specify the current config for some servers or groups.
        target-servers: ["server1"] 
        # target-groups: ["dev"]
        
        # You can overwrite common config in this command.
        # use-sudo: false
        # use-rsync: false
        # silent: false

    patch:
      - local-path: "AAA/assets/example-patch.txt"
        remote-upload: "/tmp/example-patch.txt.upload"
        remote-path: "~/examples/example-patch-remote.txt"
        remote-backup: "/tmp/example-patch-remote.txt.bak"
        target-servers: ["server1"]  
        # target-groups: ["dev"]

    execute:
      - remote-path: "~"
        scripts: 
          - "AAA/assets/example-bash.sh"
        target-servers: ["server1"]  
        # target-groups: ["dev"]

